version: '3.8'

services:
  app:
    build: .
    container_name: khqr_app
    depends_on:
      - mysql
    environment:
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: "khqr_store"
      DB_USER: "root"
      DB_PASS: "ikhode"
      BAKONG_DEV_TOKEN: ${BAKONG_DEV_TOKEN}
      BAKONG_BANK_ACCOUNT: ${BAKONG_BANK_ACCOUNT}
      BAKONG_MERCHANT_NAME: ${BAKONG_MERCHANT_NAME}
      BAKONG_MERCHANT_CITY: ${BAKONG_MERCHANT_CITY}
      ADMIN_DEFAULT_USERNAME: ${ADMIN_DEFAULT_USERNAME:-admin}
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD:-admin@2003}
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  mysql:
    image: mariadb:10.6
    container_name: khqr_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ikhode
      MYSQL_DATABASE: khqr_store
    ports:
      - "4987:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: khqr_phpmyadmin
    restart: always
    ports:
      - "9006:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ikhode
    depends_on:
      - mysql

volumes:
  mysql_data:
