services:
  app:
    build: .
    container_name: khqr_app
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: khqr_store
      DB_USER: root
      DB_PASS: ikhode
      ADMIN_DEFAULT_USERNAME: admin
      ADMIN_DEFAULT_PASSWORD: dareach@2k25
    depends_on:
      - mysql
    expose:
      - "80" # internal only; Caddy will proxy to this
    volumes:
      - .:/var/www/html

  mysql:
    image: mariadb:10.6
    container_name: khqr_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ikhode
      MYSQL_DATABASE: khqr_store
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: khqr_phpmyadmin
    restart: always
    ports:
      - "9006:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ikhode
    depends_on:
      - mysql

  caddy:
    image: caddy:latest
    container_name: khqr_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
